import { XHRUtils } from '../utils/XHRUtils';
import {MapProvider} from './MapProvider';


/**
 * Google 3D tiles provider, used to load 3D tiles using the library.
 *
 * API Reference
 *  - https://cloud.google.com/blog/products/maps-platform/create-immersive-3d-map-experiences-photorealistic-3d-tiles
 *  - https://developers.google.com/maps/documentation/tile/3d-tiles-overview
 *  - https://developers.google.com/maps/documentation/tile/create-renderer
 */
export class GoogleMaps3DTilesProvider extends MapProvider 
{
	public base: string = "https://tile.googleapis.com/";
	/**
	 * The API key that you used to access 3D Tiles service. You must attach it to all subsequent tile requests.
	 */
	public key: string = null;

	/**
	 * A built-in identifier for a 3D loading session. It's automatically generated by the API.
	 * 
	 * It must be attached by the renderer when constructing the subsequent tile requests.
	 */
	public session: string = null;

	public constructor(key: string = '') 
	{
		super();

		this.key = key;
		this.session = '';


		this.getRoot();
	}

	/**
	 * Get root tile.
	 */
	public async getRoot(): Promise<void> {
		const address = this.base + 'v1/3dtiles/root.json?key=' + this.key;

		const request = await XHRUtils.request(address, 'GET', {'Content-Type': 'text/json'}, null);

		const root = request.response.root;
		const uri = root.children[0].children[0].content.uri;

		console.log(request);
	}

	// @ts-ignore
	public fetchTile(uri: string, zoom: number, x: number, y: number): Promise<any>
	{
		const url =  this.base + uri + "?session=" + this.session + "&key=" + this.key;

		// /v1/3dtiles/datasets/CgA/files/UlRPVEYuYnVs.json?session=CIqhrPOFvdHSYg// 
		 
		// TODO <ADD CODE HERE>
		return;
	}
}
